spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/linkly
spring.datasource.username=postgres
spring.datasource.password=Future@05
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true